version: 2.1

executors:
  rust:
    docker:
      - image: rust:1.37.0-slim-buster
    working_directory: /home/circleci/repo
jobs:
  build_and_tset:
    executor: rust
    steps:
      - checkout
      - run: apt upgrade -y && apt update -y && apt install -y git
      - run: git submodule update --init --recursive --remote
      - run: rustup component add clippy
      - run: cargo clippy
      - run: cargo build --release
      - run: cargo test -- --nocapture
      - persist_to_workspace:
          root: /home/circleci
          paths:
            - repo


  package_deploy:
    executor: rust
    steps:
      - attach_workspace:
          at: /home/circleci
      - run:
          name: cargo publish
          command: |
            cargo login $CRATES_IO_API_TOKEN
            cargo publish

workflows:
  version: 2.1
  build:
    jobs:
      - build_and_tset:
          filters:
            tags:
              only: /.*/
      - package_deploy:
          requires:
            - build_and_tset
          filters:
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
            branches:
              only:
                - master
